SELECT SUB.USER_ID, SUB.NICKNAME, SUB.ADDRESS, SUB.TLNO
FROM (SELECT USER_ID, 
    NICKNAME, 
    CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS ADDRESS, 
    COUNT(*) AS writer_cnt,
    CONCAT(SUBSTR(TLNO,1,3), "-",SUBSTR(TLNO,4,4), "-", SUBSTR(TLNO,8,4)) AS TLNO
FROM USED_GOODS_BOARD UGB JOIN USED_GOODS_USER UGU
ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY WRITER_ID
HAVING writer_cnt >= 3) AS SUB
ORDER BY SUB.USER_ID DESC;