# SELECT *
# FROM MEMBER_PROFILE M
# INNER JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
# WHERE R.MEMBER_ID IN(
#     SELECT MEMBER_ID
#     FROM REST_REVIEW R2
#     GROUP BY R2.MEMBER_ID
#     HAVING COUNT(*) = (
#         SELECT MAX(CNT)
#         FROM (
#             SELECT MEMBER_ID, COUNT(*) AS CNT
#             FROM REST_REVIEW
#             GROUP BY MEMBER_ID
#         ) T
#     )
# )
# ORDER BY REVIEW_DATE, REVIEW_TEXT DESC;
SELECT 
    M.MEMBER_NAME, 
    R.REVIEW_TEXT, 
    DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM 
    MEMBER_PROFILE M JOIN REST_REVIEW R
ON 
    M.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID IN(
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
            SELECT MAX(CNT)
            FROM (SELECT COUNT(*) AS CNT
                    FROM REST_REVIEW R
                    GROUP BY R.MEMBER_ID
                 ) COUNT_LIST
          )
)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;