select FI.ID, FN.FISH_NAME, FI.LENGTH
from FISH_INFO FI join FISH_NAME_INFO FN
  on FI.FISH_TYPE = FN.FISH_TYPE
WHERE (FN.FISH_TYPE, FI.LENGTH) 
    IN (
        SELECT FISH_TYPE, MAX(LENGTH)
        FROM FISH_INFO
        GROUP BY FISH_TYPE )
order by FI.id;