/* 조회수가 가장 높은 게시믈 */


SELECT CONCAT("/home/grep/src/", UGB.BOARD_ID, "/", UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT) AS S
FROM USED_GOODS_BOARD UGB JOIN USED_GOODS_FILE UGF
ON UGB.BOARD_ID = UGF.BOARD_ID
WHERE UGB.BOARD_ID = (
    SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1
)
ORDER BY UGF.FILE_ID DESC;